# Generated by Django 2.2 on 2021-05-12 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('short_content', models.CharField(max_length=200)),
                ('date', models.DateField(auto_now_add=True)),
                ('visit_count', models.PositiveIntegerField(default=0)),
                ('image', models.ImageField(upload_to='article_images')),
            ],
        ),
    ]
