# Generated by Django 2.2 on 2021-05-12 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heart_clinic', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='short_content',
            field=models.TextField(),
        ),
    ]
