# Generated by Django 2.2 on 2021-05-12 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heart_clinic', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='short_content',
            field=models.CharField(max_length=200),
            preserve_default=False,
        ),
    ]
