# Generated by Django 2.2 on 2021-05-16 01:26

import django.core.validators
from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('heart_clinic', '0002_auto_20210512_2227'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeartConsultation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100, verbose_name='Full name')),
                ('email', models.EmailField(max_length=254)),
                ('consultation_title', models.CharField(max_length=100, verbose_name='Consultation title')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('age', models.IntegerField(validators=[django.core.validators.MaxValueValidator(150), django.core.validators.MinValueValidator(1)])),
                ('gender', models.BooleanField(choices=[(True, 'male'), (False, 'female')])),
                ('medical_history', models.CharField(max_length=2000)),
                ('consultation_description', models.CharField(max_length=2000)),
            ],
            options={
                'verbose_name': 'Heart consultation',
                'verbose_name_plural': 'Heart consultations',
            },
        ),
        migrations.AlterModelOptions(
            name='article',
            options={'verbose_name': 'Article', 'verbose_name_plural': 'Articles'},
        ),
        migrations.AlterField(
            model_name='article',
            name='content',
            field=models.TextField(verbose_name='Content'),
        ),
        migrations.AlterField(
            model_name='article',
            name='date',
            field=models.DateField(auto_now_add=True, verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='article',
            name='short_content',
            field=models.TextField(verbose_name='Short content'),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='article',
            name='visit_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Visit count'),
        ),
    ]
