# Generated by Django 2.2 on 2021-05-16 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heart_clinic', '0003_auto_20210516_0426'),
    ]

    operations = [
        migrations.AlterField(
            model_name='heartconsultation',
            name='consultation_description',
            field=models.TextField(verbose_name='Consultation description'),
        ),
        migrations.AlterField(
            model_name='heartconsultation',
            name='medical_history',
            field=models.TextField(verbose_name='Medical history'),
        ),
    ]
