# Generated by Django 2.2 on 2021-05-16 18:04

import django.core.validators
from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('heart_clinic', '0004_auto_20210516_1856'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeartConsultationSystem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField(validators=[django.core.validators.MaxValueValidator(150), django.core.validators.MinValueValidator(1)], verbose_name='Age')),
                ('chest_pain_type', models.CharField(choices=[('asympt', 'Asymptote'), ('atyp_angina', 'A typ angina'), ('typ_angina', 'typ angina'), ('non_anginal', 'Non anginal')], max_length=32, verbose_name='Chest pain type')),
                ('rest_blood_pressure', models.IntegerField(validators=[django.core.validators.MaxValueValidator(250), django.core.validators.MinValueValidator(30)], verbose_name='Rest blood pressure')),
                ('blood_sugar', models.CharField(choices=[('FALSE', 'False'), ('True', 'True')], max_length=32, verbose_name='Blood sugar')),
                ('rest_electro', models.CharField(choices=[('normal', 'Normal'), ('left_vent_hyper', 'Left vent hyper'), ('st_t_wave_abnormality', 'st_t_wave_abnormality')], max_length=32, verbose_name='Rest electro')),
                ('max_heart_rate', models.IntegerField(validators=[django.core.validators.MaxValueValidator(250), django.core.validators.MinValueValidator(30)], verbose_name='Max heart rate')),
                ('exercice_angina', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], max_length=32, verbose_name='Exercice angina')),
                ('disease', models.CharField(choices=[('positive', 'Positive'), ('negative', 'Negative')], max_length=32, verbose_name='Disease')),
            ],
            options={
                'verbose_name': 'Heart consultation system',
                'verbose_name_plural': 'Heart consultations system',
            },
        ),
        migrations.AlterField(
            model_name='heartconsultation',
            name='age',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(150), django.core.validators.MinValueValidator(1)], verbose_name='Age'),
        ),
        migrations.AlterField(
            model_name='heartconsultation',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='heartconsultation',
            name='gender',
            field=models.BooleanField(choices=[(True, 'male'), (False, 'female')], verbose_name='Gender'),
        ),
        migrations.AlterField(
            model_name='heartconsultation',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name='Phone number'),
        ),
    ]
